### PR TITLE
issue 64 add junit 5 support

### LINKED ISSUE #64: Check Flink 1.17 compatibility
Run connector on Flink 1.17
Add build configuration for 1.17
Update Readme.md

In case of bigger issues with 1.15, drop the support for it.

### PR DESCRIPTION
**Pull request by davidradl**
#### Description

Add junit 5 support - so tests can run against Flink 1.17 and 1.18 
Resolves #64 

##### PR Checklist
- [x] Tests added (enabled tests)
- [x] [Changelog](CHANGELOG.md) updated

### CODE REVIEW

**Comment by kristoffSC** [comment]
checking

**Comment by kristoffSC** [comment]
checking.

**Comment by kristoffSC** [comment]
Hi @davidradl 
Please try this patch on your branch and let me know what are the results

[Flink1.16.patch](https://github.com/getindata/flink-http-connector/files/14629293/Flink1.16.patch)

**Comment by kristoffSC** [comment]
I see thatbuild fails with below exception
```
Error: 9,649 [ERROR]   HttpSinkConnectionTest.testFailedConnection:238 expected: <1> but was: <0>
Error: 9,649 [ERROR]   HttpSinkConnectionTest.testServerErrorConnection:202 expected: <1> but was: <0>
```

It is an improvement comparing to previous thing where thre was classNoFound ;)
I will take a look at those two tests, maybe I will find what causing the issue here.

**Comment by davidradl** [comment]
> I see thatbuild fails with below exception
> 
> ```
> Error: 9,649 [ERROR]   HttpSinkConnectionTest.testFailedConnection:238 expected: <1> but was: <0>
> Error: 9,649 [ERROR]   HttpSinkConnectionTest.testServerErrorConnection:202 expected: <1> but was: <0>
> ```
> 
> It is an improvement comparing to previous thing where thre was classNoFound ;) I will take a look at those two tests, maybe I will find what causing the issue here.
> 
> UPDATE: This is working on Flink 1.16.3 interesting i bet we are doing something wrong in test for metric gathering.

@kristoffSC thanks let me know how you get on.

**Comment by davidradl** [comment]
this pr may address [https://github.com/getindata/flink-http-connector/issues/73](https://github.com/getindata/flink-http-connector/issues/73)

**Comment by kristoffSC** [comment]
Hi @davidradl 
Please apply attached patch on top of what you have currently on this branch.
This should do the job.

I've ran local builds against Flink 1.16, 17 and 18 they all passing.

[Flink1.16_b.patch](https://github.com/getindata/flink-http-connector/files/14733690/Flink1.16_b.patch)

**Comment by davidradl** [comment]
@kristoffSC It is working - thanks for the patches - I have squashed the commits. I think we are ready to merge.

**Review by kristoffSC — APPROVED** [review]

**Pull request merged**
